#!/bin/sh

# Questo è lo script principale per gestire le jail su FreeBSD

# Include the configuration file

FBJ_DIR="/usr/local/etc/fbj"

if [ -d "~/.local/share/fbj" ]; then
    FBJ_DIR="$HOME/.local/share/fbj"
fi

CONFIG_FILE_USER="$FBJ_DIR/fbj.conf"
CONFIG_FILE_SYSTEM="$FBJ_DIR/fbj-system.conf"

if [ -f "$CONFIG_FILE_USER" ] && [ -f "$CONFIG_FILE_SYSTEM" ]; then
    . "$CONFIG_FILE_USER"
    . "$CONFIG_FILE_SYSTEM"
else
    echo "Configuration file not found"
    exit 1
fi

jail_name="$2"

# Verifica che lo script sia eseguito con i privilegi di root
if [ "$(id -u)" -ne 0 ]; then
    echo "Sorry, you must be root to run this script."
    exit 1
fi

if [ -z "$2" ] && { [ "$1" != "update" ] && [ "$1" != "init" ]; }
then
  read -p "Nome jail:" jail_name
fi

case $1 in
    create)
        shift 1
        sh $CREATE_JAIL "$@"
        ;;
    update)
        sh $UPDATE_JAIL "$jail_name" "$3"
        ;;
    upgrade)
        sh $UPGRADE_JAIL "$jail_name" "$3"
        ;;    
    delete)
        sh $DELETE_JAIL "$jail_name"
        ;;
    rename)
        sh $RENAME_JAIL "$jail_name" "$3"
        ;;
    start | stop | restart | autostart)
        sh $JAIL_BOOT "$1" "$jail_name"
        ;;
    init)
        ee "$CONFIG_DIR/fbj.conf"
        sh $UTILITIES_DIR/utility-init.sh
        ;;
    *)
        echo "Utilizzo: $0 [create|update|upgrade|delete|rename|start|stop|restart|autostart|init]"
        echo "$0 create name ip1 (bridge1) (ip2) (bridge2) (start) (autostart)"
        echo "$0 update (name) (base|pkg)"
        echo "$0 upgrade name RELEASE"
        echo "$0 delete name"
        echo "$0 rename name (newname)"
        echo "$0 start|stop|restart|autostart name"
        echo "$0 init"
        ;;
esac