#!/bin/sh

# Includi il file di configurazione
CONFIG_FILE_USER="/usr/local/etc/fbj/fbj.conf"
CONFIG_FILE_SYSTEM="/usr/local/etc/fbj/fbj-system.conf"
if [ -f "$CONFIG_FILE_USER" ] && [ -f "$CONFIG_FILE_SYSTEM" ]; then
    . "$CONFIG_FILE_USER"
    . "$CONFIG_FILE_SYSTEM"
else
    echo "Configuration file not found"
    exit 1
fi

nameserver_file="$1"
jail_gw="$2"
jail_dns="$CUSTOM_DNS"
jail_dns_2="$CUSTOM_DNS_2"

if [ "$DEFAULT_NAMESERVER" != "host" ]; then
    if [ "$DEFAULT_NAMESERVER" = "auto" ]; then
        jail_dns="$jail_gw"
    fi
    echo "# Generated by fbj" > "$nameserver_file"
    echo "nameserver $jail_dns" >> "$nameserver_file"
    if [ "$DEFAULT_NAMESERVER" = "custom" ]; then
        echo "nameserver $jail_dns_2" >> "$nameserver_file"
    fi
else
    cp "/etc/resolv.conf" "$nameserver_file"
fi