#!/bin/sh

# Include the configuration file

CONFIG_DIR="/usr/local/etc/fbj"

CONFIG_FILE_USER="$CONFIG_DIR/fbj.conf"
CONFIG_FILE_SYSTEM="$CONFIG_DIR/fbj-system.conf"

if [ -f "$CONFIG_FILE_USER" ] && [ -f "$CONFIG_FILE_SYSTEM" ]; then
    . "$CONFIG_FILE_USER"
    . "$CONFIG_FILE_SYSTEM"
else
    printf "Configuration file not found\n"
    exit 1
fi

nameserver_file="$1"
jail_gw="$2"
jail_dns="$CUSTOM_DNS"
jail_dns_2="$CUSTOM_DNS_2"

if [ "$DEFAULT_NAMESERVER" != "host" ]; then
    if [ "$DEFAULT_NAMESERVER" = "auto" ]; then
        jail_dns="$jail_gw"
    fi
    printf "# Generated by fbj\n" > "$nameserver_file"
    printf "nameserver %s" "$jail_dns" >> "$nameserver_file"
    if [ "$DEFAULT_NAMESERVER" = "custom" ]; then
        printf "\nnameserver %s" "$jail_dns_2" >> "$nameserver_file"
    fi
else
    cp "/etc/resolv.conf" "$nameserver_file"
fi